# Generated by Django 5.1.6 on 2025-04-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdentityInf0',
            new_name='IdentityInfo',
        ),
        migrations.RenameIndex(
            model_name='identityinfo',
            new_name='administrat_id_4c3555_idx',
            old_name='administrat_id_587212_idx',
        ),
    ]
