# Generated by Django 5.1.6 on 2025-04-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_is_cds_leader_user_is_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_chat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_comment',
        ),
        migrations.AddField(
            model_name='user',
            name='can_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_request',
            field=models.BooleanField(default=False),
        ),
    ]
