# Generated by Django 5.1.6 on 2025-04-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_rename_identityinf0_identityinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_post',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_request',
        ),
    ]
