# Generated by Django 5.1.6 on 2025-04-12 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_user_can_chat_remove_user_can_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityInf0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie', models.ImageField(upload_to='')),
                ('driver_licenses', models.ImageField(upload_to='')),
                ('ID', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='userverification',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['-user', '-token'], name='administrat_user_id_c31202_idx'),
        ),
        migrations.AddField(
            model_name='identityinf0',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='identityinf0',
            index=models.Index(fields=['-id'], name='administrat_id_587212_idx'),
        ),
    ]
