# Generated by Django 5.1.6 on 2025-04-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_user_can_post_remove_user_can_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityinfo',
            name='ID_no',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='driver_licenses',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='identityinfo',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
