# Generated by Django 5.1.6 on 2025-05-01 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=160, null=True)),
                ('value', models.CharField(blank=True, max_length=160, null=True)),
                ('reason', models.CharField(blank=True, max_length=1600, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
