# Generated by Django 5.1.6 on 2025-04-13 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('date_of_departure', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_seat', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('to_bal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_request', models.TextField(blank=True, null=True)),
                ('seat_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'online'), ('pay on arrival', 'pay on arrival'), ('pay in car park', 'pay in car park')], max_length=20, null=True)),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='backendLogic.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_passengers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('plate_no', models.CharField(max_length=150)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleinfo', to='backendLogic.ride')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id', '-is_active'], name='backendLogi_id_2f81f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('description', models.CharField(max_length=500)),
                ('ref', models.CharField(max_length=500)),
                ('date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-id'], name='backendLogi_id_9a0d8d_idx')],
            },
        ),
    ]
