# Generated by Django 5.1.6 on 2025-04-07 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendLogic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('description', models.CharField(max_length=500)),
                ('ref', models.CharField(max_length=500)),
                ('date', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-id']},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['-id', '-is_active'], name='backendLogi_id_2f81f3_idx'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-id'], name='backendLogi_id_9a0d8d_idx'),
        ),
    ]
