# Generated by Django 5.1.6 on 2025-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendLogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tran_type',
            field=models.CharField(choices=[('debit', 'debit'), ('credit', 'credit'), ('sub', 'sub')], default='credit', max_length=500),
        ),
    ]
