# Generated by Django 5.1.6 on 2025-04-07 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendLogic', '0002_transaction_alter_subscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('date_of_departure', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_seat', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('to_bal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_request', models.TextField(blank=True, null=True)),
                ('seat_taken', models.PositiveIntegerField(blank=True, null=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'online'), ('pay on arrival', 'pay on arrival'), ('pay in car park', 'pay in car park')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_passengers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('plate_no', models.CharField(max_length=150)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleinfo', to='backendLogic.ride')),
            ],
        ),
    ]
