# Generated by Django 5.1.6 on 2025-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendLogic', '0002_transaction_tran_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ride',
            name='to_bal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=80),
        ),
        migrations.AlterField(
            model_name='ride',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=80),
        ),
    ]
