# Generated by Django 5.1.6 on 2025-04-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendLogic', '0003_alter_ride_price_per_seat_alter_ride_to_bal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepassenger',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', help_text='Current passenger status', max_length=10),
        ),
    ]
