# Generated by Django 5.1.6 on 2025-05-01 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendLogic', '0004_ridepassenger_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('date_of_departure', models.DateTimeField(default=django.utils.timezone.now)),
                ('budget_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=80)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'online'), ('pay on arrival', 'pay on arrival'), ('pay in car park', 'pay in car park')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rideRequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
